name: parameterized_test
description: Run a test multiple times based on provided parameter list. Inspired by JUnit ParameterizedTest.
version: 2.1.0
homepage: https://www.github.com/DutchCodingCompany/parameterized_test

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  meta: ^1.16.0
  stack_trace: ^1.11.1
  test: ^1.26.3

dev_dependencies:
  csv: ^6.0.0
  very_good_analysis: ^6.0.0
